force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CloseOldPositionSchedulerTest.cls
@isTest
private class CloseOldPositionSchedulerTest {
  @isTest
  static void testScheduler() {
    Test.startTest();

    Position__c position = TestDataFactory.createPosition('Test');
    insert position;

    Id jobId = System.schedule(
      'testScheduler',
      '0 0 0 * * ?',
      new CloseOldPositionScheduler()
    );

    CronTrigger ct = [
      SELECT Id, CronExpression, TimesTriggered, NextFireTime
      FROM CronTrigger
      WHERE id = :jobId
    ];

    Assert.areEqual(
      '0 0 0 * * ?',
      ct.CronExpression,
      'The CronExpressions are not the same, get: ' + ct.CronExpression
    );

    Assert.areEqual(0, ct.TimesTriggered, 'The job is running!');
    Assert.areEqual(
      '2024-04-23 00:00:00',
      String.valueOf(ct.NextFireTime),
      'The expected next time the job will did not meet, instead get: ' +
      String.valueOf(ct.NextFireTime)
    );
    Test.stopTest();

    Assert.areEqual(
      'Test',
      [SELECT Id, Title__c FROM Position__c WHERE Id = :position.Id].Title__c,
      'The expected result is Test'
    );
  }
}