force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <defaultValue>(TODAY())</defaultValue>
    <label>Open Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PositionsListWithControllerLWC.cls
public with sharing class PositionsListWithControllerLWC {
  @AuraEnabled(cacheable=true)
  public static List<Position__c> getPositions(String status) {
    List<String> selectedStatuses = status == '' ||
      status == null
      ? new List<String>{ 'Open', 'Closed', 'Pending' }
      : new List<String>{ status };
    return [
      SELECT
        Id,
        Title__c,
        Status__c,
        Open_Date__c,
        Closed_Date__c,
        Min_Pay__c,
        Max_Pay__c
      FROM Position__c
      WHERE Status__c IN :selectedStatuses
    ];
  }

  @AuraEnabled
  public static void updatePositions(List<Position__c> updatedData) {
    update updatedData;
  }
}