force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <defaultValue>(TODAY())</defaultValue>
    <label>Open Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseOldPositionsBatchble.cls
public class CloseOldPositionsBatchble implements Database.Batchable<SObject> {
  private static final Date TODAY_MINUS_3_MONTHS = Date.today().addDays(-90);
  private static final String OPEN_STATUS = 'Open';

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'SELECT Id, Status__c, Open_Date__c FROM Position__c WHERE Status__c = :OPEN_STATUS AND Open_Date__c <= :TODAY_MINUS_3_MONTHS'
    );
  }

  public void execute(Database.BatchableContext bc, List<Position__c> scope) {
    CloseOldPositionsBatchbleHelper.closeOldPositions(scope);
  }

  public void finish(Database.BatchableContext bc) {
  }
}