force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PositionTriggerTest.cls
@isTest
public with sharing class PositionTriggerTest {
  @isTest
  static void testAddClosedDateToPosition() {
    Position__c positionInsert = TestDataFactory.createPosition('Test');
    positionInsert.Status__c = 'Closed';
    Test.startTest();
    insert positionInsert;
    Test.stopTest();

    Position__c closedPosition = [
      SELECT Closed_Date__c, Id, Status__c
      FROM Position__c
      WHERE Status__c = 'Closed' AND Title__c = 'Test'
      LIMIT 1
    ];

    Assert.areNotEqual(
      null,
      closedPosition.Closed_Date__c,
      'The expected result is date, but insted get:' +
      closedPosition.Closed_Date__c
    );
  }
}