force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <defaultValue>(TODAY())</defaultValue>
    <label>Open Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CloseOldPositionsBatchableTest.cls
@isTest
private class CloseOldPositionsBatchableTest {
  @TestSetup
  static void makePositions() {
    Test.startTest();
    List<Position__c> positions = new List<Position__c>();
    for (Integer i = 0; i < 200; i++) {
      Position__c position = TestDataFactory.createPosition('Test');
      position.Open_Date__c = Date.today().addDays(-100);
      position.Status__c = 'Open';
      positions.add(position);
    }
    insert positions;
    Test.stopTest();
  }

  @isTest
  static void testCloseOldPositionsBatchble() {
    Test.startTest();
    CloseOldPositionsBatchble closeOldPositions = new CloseOldPositionsBatchble();
    Id batchID = Database.executeBatch(closeOldPositions, 200);
    Test.stopTest();

    Assert.areEqual(
      200,
      [
        SELECT COUNT()
        FROM Position__c
        WHERE Title__c = 'Test' AND Status__c = 'Closed'
      ],
      'Batcheble does not work'
    );
  }
}