force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PositionListWithControllerLWCTest.cls
@isTest
private class PositionListWithControllerLWCTest {
  @TestSetup
  static void makeData() {
    Test.startTest();
    List<Position__c> positions = new List<Position__c>();
    List<String> statuses = new List<String>{ 'Open', 'Closed', 'Pending' };
    for (String status : statuses) {
      positions.add(
        new Position__c(
          Title__c = 'Position',
          Status__c = status,
          Location__c = 'Test'
        )
      );
    }
    insert positions;
    Test.stopTest();
  }

  @isTest
  static void testUpdatePositions() {
    Test.startTest();
    List<Position__c> positions = PositionsListWithControllerLWC.getPositions(
      '',
      3,
      0
    );
    positions[0].Title__c = 'New Title';
    PositionsListWithControllerLWC.updatePositions(positions);
    Test.stopTest();

    List<Position__c> updatedPositions = [
      SELECT Id, Title__c
      FROM Position__c
      WHERE Title__c = 'New Title'
    ];

    Assert.areEqual(
      1,
      updatedPositions.size(),
      'The expected size of updated positions is 1, but instead get: ' +
      updatedPositions.size()
    );
  }

  @isTest
  static void testGetCountPositions() {
    Test.startTest();
    Integer positionCount = PositionsListWithControllerLWC.getCountPositions(
      ''
    );
    Integer closedPositionCount = PositionsListWithControllerLWC.getCountPositions(
      'Closed'
    );
    Test.stopTest();

    Assert.areEqual(
      3,
      positionCount,
      'The expected count of all positions is 3, but instead get: ' +
      positionCount
    );

    Assert.areEqual(
      1,
      closedPositionCount,
      'The expected count of closed positions is 1, but instead get: ' +
      closedPositionCount
    );
  }

  @isTest
  static void testGetPositions() {
    Test.startTest();
    List<Position__c> positions = PositionsListWithControllerLWC.getPositions(
      '',
      3,
      0
    );
    List<Position__c> closedPositions = PositionsListWithControllerLWC.getPositions(
      'Closed',
      3,
      0
    );
    Test.stopTest();

    Assert.areEqual(
      3,
      positions.size(),
      'The expected size of all positions is 3, but instead get: ' +
      positions.size()
    );

    Assert.areEqual(
      1,
      closedPositions.size(),
      'The expected size of Closed positions is 1, but instead get: ' +
      closedPositions.size()
    );
    Assert.areEqual(
      'Closed',
      closedPositions[0].Status__c,
      'The expected value of Status__c positions is Closed, but instead get: ' +
      closedPositions[0].Status__c
    );
  }
}