force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public with sharing class PositionTriggerHandler {
  public static List<Position__c> getPositionsWithChangedStatusToClosed(Map<Id, Position__c> positionsNewMap, Map<Id, Position__c> positionOldMap) {
    List<Position__c> changedPositions = new List<Position__c>();
    for(Id positionId : positionsNewMap.keySet()) {
      Position__c newPosition = positionsNewMap.get(positionId);
      if(newPosition.Status__c != positionOldMap.get(positionId).Status__c && newPosition.Status__c == 'Closed') {
        changedPositions.add(newPosition);
      }
    }
    return changedPositions;
  }

  public static void addClosedDateToPosition(List<Position__c> positions) {
    for (Position__c position : positions) {
      if (position.Status__c == 'Closed') {
        position.Closed_Date__c = Date.today();
      }
    }
  }
}