force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Full_Rating__c.field-meta.xml
<CustomField>
    <fullName>Full_Rating__c</fullName>
    <label>Full Rating</label>
    <summarizedField>Review__c.Rating__c</summarizedField>
    <summaryForeignKey>Review__c.Job_Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Number_Of_Reviews__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Reviews__c</fullName>
    <label>Number Of Reviews</label>
    <summaryForeignKey>Review__c.Job_Application__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula
  >IF(AND(Number_Of_Reviews__c &gt; 0, !ISNULL(Full_Rating__c)), Full_Rating__c  /  Number_Of_Reviews__c, 0)</formula>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Need review</fullName>
                <default>true</default>
                <label>Need review</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Need review</fullName>
                <default>true</default>
                <label>Need review</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewTriggerHandler.cls
public with sharing class ReviewTriggerHandler {
  public static List<Review__c> getReviewsWithChangedRating(Map<Id, Review__c> reviewsNewMap, Map<Id, Review__c> reviewsOldMap) {
    List<Review__c> changedReviews = new List<Review__c>();
    for(Id reviewId : reviewsNewMap.keySet()) {
      Review__c newPosition = reviewsOldMap.get(reviewId);
      if(reviewsNewMap.get(reviewId).Rating__c != reviewsOldMap.get(reviewId).Rating__c) {
        changedReviews.add(newPosition);
      }
    }
    return changedReviews;
  }
  
  public static void updateJobApplicationRatingAndReviews(
    List<Review__c> reviews,
    Boolean isDeleted
  ) {
    Set<Id> jobApplicationIds = new Set<Id>();
    Map<Id, Decimal> fullRatings = new Map<Id, Decimal>();
    Map<Id, Integer> numbersOfReviews = new Map<Id, Integer>();

    for (Review__c relatedReview : reviews) {
      Id jobApplicationId = relatedReview.Job_Application__c;
      jobApplicationIds.add(jobApplicationId);

      if(relatedReview.Status__c == 'Reviewed') {
        Decimal newFullRating = fullRatings.get(jobApplicationId);
        if (newFullRating == null) {
          newFullRating = 0;
        }
        if (relatedReview.Rating__c != null) {
          if(isDeleted) {
            newFullRating -= relatedReview.Rating__c;
          } else {
            newFullRating += relatedReview.Rating__c;
          }
        }
        fullRatings.put(jobApplicationId, newFullRating);
  
        Integer newNumberOfReviews = numbersOfReviews.get(
          jobApplicationId
        );
        if (newNumberOfReviews == null) {
          newNumberOfReviews = 0;
        }
        if(!isDeleted) {
          newNumberOfReviews += 1;
        } else {
          newNumberOfReviews -= 1;
        } 
        numbersOfReviews.put(
          jobApplicationId,
          newNumberOfReviews
        );  
      } else {
        numbersOfReviews.put(
          jobApplicationId,
          0
        );  
        fullRatings.put(jobApplicationId, 0);
      }
    }

    List<Job_Application__c> jobApplications = new List<Job_Application__c>();

    for (Job_Application__c jobApplication : [
      SELECT Id, Number_Of_Reviews__c, Full_Rating__c
      FROM Job_Application__c
      WHERE Id IN :jobApplicationIds
    ]) {
      if(jobApplication.Number_Of_Reviews__c != null) {
      jobApplication.Number_Of_Reviews__c += numbersOfReviews.get(
        jobApplication.Id
      );        
      } else {
        jobApplication.Number_Of_Reviews__c = numbersOfReviews.get(
          jobApplication.Id
        ); 
      }
      if(jobApplication.Full_Rating__c != null) {
        jobApplication.Full_Rating__c += fullRatings.get(jobApplication.Id);
      } else {
        jobApplication.Full_Rating__c = fullRatings.get(jobApplication.Id);
      }
      

      jobApplications.add(jobApplication);
    }

    if (!jobApplications.isEmpty()) {
      update jobApplications;
    }
  }
}