force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only open positions</errorMessage>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Need review</fullName>
                <default>true</default>
                <label>Need review</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler {
  public static List<Job_Application__c> getJobApplicationsWithChangedStatusToAccepted(Map<Id, Job_Application__c> jobApplicationNewMap, Map<Id, Job_Application__c> jobApplicationOldMap) {
    List<Job_Application__c> changedJobApplications = new List<Job_Application__c>();
    for(Id jobApplicationId : jobApplicationNewMap.keySet()) {
      Job_Application__c newJobApplication = jobApplicationNewMap.get(jobApplicationId);
      if(newJobApplication.Status__c != jobApplicationOldMap.get(jobApplicationId).Status__c && newJobApplication.Status__c == 'Accepted') {
        changedJobApplications.add(newJobApplication);
      }
    }
    return changedJobApplications;
  }
  
  public static void closeRelatedPosition(
    List<Job_Application__c> jobApplications
  ) {
    Set<String> positionIds = new Set<String>();
    for (Job_Application__c jobApplication : jobApplications) {
      positionIds.add(jobApplication.Position__c);
    }

    Map<Id, Position__c> positions = new Map<Id, Position__c>(
      [SELECT Id, Status__c FROM Position__c WHERE Id IN :positionIds]
    );

    Map<Id, Position__c> positionsToUpdateMap = new Map<Id, Position__c>();
    for (Job_Application__c jobApplication : jobApplications) {
      if (jobApplication.Status__c == 'Accepted') {
        Position__c position = positions.get(jobApplication.Position__c);
        if(!positionsToUpdateMap.containsKey(position.Id)) {
          position.Status__c = 'Closed';
          positionsToUpdateMap.put(position.Id, position);          
        }
      }
    }

    if (!positionsToUpdateMap.isEmpty()) {
      update positionsToUpdateMap.values();
    }
  }
}