force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateAndJobApplicationModal.cls
public with sharing class CandidateAndJobApplicationModal {
  @AuraEnabled(cacheable=true)
  public static List<String> getFormFieldsByObjectType(String sObjectType) {
    Create_Candidate_Setting__mdt mtd = getMetadata();
    return generateFieldsArray(
      getFieldSetFields(sObjectType, (String) mtd.get(sObjectType))
    );
  }

  private static List<String> generateFieldsArray(
    List<Schema.FieldSetMember> fields
  ) {
    List<String> form = new List<String>();
    for (Schema.FieldSetMember field : fields) {
      form.add(field.getFieldPath());
    }
    return form;
  }

  private static List<Schema.FieldSetMember> getFieldSetFields(
    String sObjectApiName,
    String fieldSetName
  ) {
    Schema.SObjectType sObjectType = Schema.getGlobalDescribe()
      .get(sObjectApiName);
    if (sObjectType == null) {
      return new List<Schema.FieldSetMember>();
    }
    Schema.DescribeSObjectResult sObjectDescribe = sObjectType.getDescribe();
    Schema.FieldSet fieldSet = sObjectDescribe.fieldSets.getMap()
      .get(fieldSetName);
    return fieldSet != null
      ? fieldSet.getFields()
      : new List<Schema.FieldSetMember>();
  }

  private static Create_Candidate_Setting__mdt getMetadata() {
    return [
      SELECT Candidate__c, Job_Application__c
      FROM Create_Candidate_Setting__mdt
      WHERE QualifiedApiName = 'Universal_Modal'
      LIMIT 1
    ];
  }
}