force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only open positions</errorMessage>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>Job_Application__r.Position__r.Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordManagerTest.cls
@isTest
private class RecordManagerTest {
  @TestSetup
  static void makeData() {
    Id profileId = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Recruiter'
      LIMIT 1
    ]
    .Id;
    User testUser = TestDataFactory.createUser(profileId, 1);
    insert testUser;
    User testRecruiter = [
      SELECT Id
      FROM User
      WHERE ProfileId = :profileId AND IsActive = TRUE
      LIMIT 1
    ];

    System.runAs(testRecruiter) {
      List<SObject> objs = new List<SObject>();
      for (Integer i = 0; i < 4; i++) {
        objs.add(TestDataFactory.createPosition('Developer Title'));
        objs.add(TestDataFactory.createCandidate('Last Name developer'));
      }
      insert objs;

      Id positionId = [SELECT Id FROM Position__c LIMIT 1].Id;
      Id candidateId = [SELECT Id FROM Candidate__c LIMIT 1].Id;
      Job_Application__c jobApplication = TestDataFactory.createJobApplication(
        positionId,
        candidateId
      );
      insert jobApplication;

      Id jobApplicationId = [SELECT Id FROM Job_Application__c LIMIT 1].Id;
      List<Review__c> reviews = new List<Review__c>();
      for (Integer i = 0; i < 4; i++) {
        reviews.add(
          TestDataFactory.createReview('develop FeedBack', jobApplicationId)
        );
      }
      insert reviews;
    }
  }

  @isTest
  static void testSelectJobApplicationsWithReviewsCreatedLastWeek() {
    List<Job_Application__c> jobApplications = RecordManager.selectJobApplicationsWithReviewsCreatedLastWeek();
    Assert.areEqual(
      1,
      jobApplications.size(),
      'The expected size of list is 1, but instead get: ' +
      jobApplications.size()
    );
  }

  @isTest
  static void testGetOldDevelopRecords() {
    List<Id> objIds = new List<Id>();
    for (Position__c pos : [SELECT Id FROM Position__c]) {
      objIds.add(pos.Id);
    }
    for (Candidate__c candidate : [SELECT Id FROM Candidate__c]) {
      objIds.add(candidate.Id);
    }
    for (Review__c review : [SELECT Id FROM Review__c]) {
      objIds.add(review.Id);
    }
    for (Id objId : objIds) {
      Test.setCreatedDate(objId, Date.today().addDays(-100));
    }

    Test.startTest();
    Test.setFixedSearchResults(objIds);
    List<List<SObject>> result = RecordManager.selectOldRecordsWithKeyword(
      'develop'
    );
    Test.stopTest();

    Assert.areNotEqual(
      true,
      result == null || result.isEmpty(),
      'Result cannot be empty!'
    );

    for (List<SObject> sub : result) {
      Assert.areEqual(
        4,
        sub.size(),
        'The expected size of list is 4, but instead get: ' + sub.size()
      );
    }
  }
}