force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Cover_Letter__c.field-meta.xml
<CustomField>
    <fullName>Cover_Letter__c</fullName>
    <label>Cover Letter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only open positions</errorMessage>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Need review</fullName>
                <default>true</default>
                <label>Need review</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerTest.cls
@isTest
public with sharing class JobApplicationTriggerTest {
  @isTest
  static void testCloseRelatedPosition() {
    List<Position__c> positions = new List<Position__c>();
    for (Integer i = 0; i < 1000; i++) {
      positions.add(TestDataFactory.createPosition('Test'));
    }
    Candidate__c candidate = TestDataFactory.createCandidate('Test');
    Test.startTest();
    insert positions;
    insert candidate;
    Id candidateId = [
      SELECT Id
      FROM Candidate__c
      WHERE Last_Name__c = 'Test'
      LIMIT 1
    ]
    .Id;
    positions = [
      SELECT Id
      FROM Position__c
      WHERE Title__c = 'Test'
    ];
    List<Job_Application__c> jobApplications = new List<Job_Application__c>();
    for (Integer i = 0; i < 1000; i++) {
      Job_Application__c jobApplication = TestDataFactory.createJobApplication(
        positions.get(i).Id,
        candidateId
      );
      jobApplication.Status__c = 'Need Review';
      jobApplications.add(jobApplication);
    }
    insert jobApplications;

    List<Job_Application__c> jobApplicationsToUpdate = [SELECT Id, Status__c, Cover_Letter__c FROM Job_Application__c WHERE Status__c = 'Need Review'];
    Integer halfSize = jobApplicationsToUpdate.size() / 2;
    
    for(Integer i = 0; i < halfSize; i++) {
      jobApplicationsToUpdate.get(i).Status__c = 'Accepted';
    }
    
    for(Integer i = halfSize; i < jobApplicationsToUpdate.size(); i++) {
      jobApplicationsToUpdate.get(i).Cover_Letter__c = 'New';
    }
    
    update jobApplicationsToUpdate;
    Test.stopTest();
    List<Job_Application__c> insertedJobApplications = [
      SELECT Id, Position__r.Status__c
      FROM Job_Application__c
      WHERE Position__c = :positions AND Position__r.Status__c = 'Closed'
    ];

    Assert.areEqual(
      halfSize,
      insertedJobApplications.size(),
      'The expected result is '+ halfSize + ', but instead get: ' +
      insertedJobApplications.size()
    );
  }
}